name: Deploy to Elastic Beanstalk

on:
  push:
    branches: [main]

env:
  RUN_NUMBER: ${{ github.run_number }}
  AWS_S3_BUCKET: ${{ secrets.AWS_BUCKET }}
  AWS_SECRET_KEY_ID: ${{ secrets.AWS_AGENCIA_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_AGENCIA_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_AGENCIA_REGION }}

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    environment: inteligente-marketing

    steps:
      - uses: actions/checkout@master
      - name: Use node 16
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_SECRET_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install
        env:
          NODE_ENV: development
        run: |
          npm install

      - name: Build, and export
        env:
          NODE_ENV: production
        run: |
          npm run build
          npm run export

      - name: AWS CLI Upload version file
        run: |
          aws s3 cp out s3://${{ env.AWS_S3_BUCKET }} --recursive
          aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_AGENCIA_CLOUDFRONT }} --paths "/*"
